workflows:
  # Workflow cho Development - Build APK
  android-dev:
    name: Android Dev Build
    max_build_duration: 60
    instance_type: linux_x2
    environment:
      flutter: stable
      groups:
        - keystore_credentials # Android signing credentials (nếu cần)
      vars:
        FLAVOR: "dev"
    scripts:
      - name: Get Flutter dependencies
        script: |
          flutter pub get
          flutter pub run build_runner build --delete-conflicting-outputs
      - name: Build Android APK
        script: |
          flutter build apk --flavor dev --dart-define=ENV=DEV --release
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
      - build/app/outputs/mapping/dev/release/mapping.txt
    publishing:
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: true

  # Workflow cho Staging - Build AAB
  android-staging:
    name: Android Staging Build
    max_build_duration: 60
    instance_type: linux_x2
    environment:
      flutter: stable
      groups:
        - keystore_credentials # Android signing credentials
      vars:
        FLAVOR: "stag"
    scripts:
      - name: Get Flutter dependencies
        script: |
          flutter pub get
          flutter pub run build_runner build --delete-conflicting-outputs
      - name: Build Android App Bundle
        script: |
          flutter build appbundle --flavor stag --dart-define=ENV=STAGING --release
    artifacts:
      - build/app/outputs/bundle/stagRelease/*.aab
      - build/app/outputs/mapping/stag/release/mapping.txt
    publishing:
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: true

  # Workflow cho Production - Build AAB
  android-production:
    name: Android Production Build
    max_build_duration: 60
    instance_type: linux_x2
    environment:
      flutter: stable
      groups:
        - keystore_credentials # Android signing credentials
      vars:
        FLAVOR: "prod"
    scripts:
      - name: Get Flutter dependencies
        script: |
          flutter pub get
          flutter pub run build_runner build --delete-conflicting-outputs
      - name: Build Android App Bundle
        script: |
          flutter build appbundle --flavor prod --dart-define=ENV=PRODUCTION --release
    artifacts:
      - build/app/outputs/bundle/prodRelease/*.aab
      - build/app/outputs/mapping/prod/release/mapping.txt
    publishing:
      email:
        recipients:
          - nguyenngoctuyen188@gmail.com
        notify:
          success: true
          failure: true
      # Uncomment để tự động upload lên Google Play
      # google_play:
      #   credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
      #   track: production # hoặc internal, alpha, beta
