workflows:
  # Workflow cho Development - Build APK
  android-dev:
    name: Android Dev Build
    max_build_duration: 60
    instance_type: linux_x2
    environment:
      flutter: stable
      groups:
        - keystore_credentials # Android signing credentials (nếu cần)
      vars:
        FLAVOR: "dev"
    scripts:
      - name: Get Flutter dependencies
        script: |
          flutter pub get
          flutter pub run build_runner build --delete-conflicting-outputs
      - name: Build Android APK
        script: |
          flutter build apk --flavor dev --dart-define=ENV=DEV --release
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
      - build/app/outputs/mapping/dev/release/mapping.txt
    publishing:
      email:
        recipients:
          - nguyenngoctuyen188@gmail.com
        notify:
          success: true
          failure: true
